workloads:
  instanceTypes:
    additional:
      1xT4:
        resources:
          CPU: 12
          GPU: 1
          memory: 92Gi
          accelerators:
            - T4
      8xA100:
        resources:
          CPU: 92
          GPU: 8
          memory: 864Gi
          accelerators:
            - A100-40G