workloads:
  instanceTypes:
    additional:
      1xA100:
        resources:
          CPU: 18 # should be less than the total CPU of the node
          GPU: 1
          memory: 192Gi
          accelerators:
            - A100-80G
      8xA100:
        resources:
          CPU: 90
          GPU: 8
          memory: 1792Gi
          accelerators:
            - A100-80G